spring:
  datasource:
    url: jdbc:mysql://localhost:3306/re_wear_db?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: dbsl2023!
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

center:
  datasource:
    url: jdbc:mysql://localhost:3306/center?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: dbsl2023!
    driver-class-name: com.mysql.cj.jdbc.Driver